enum ScreenList {
  ONBOARDING = 'ONBOARDING',
  AUTH_LOGIN = 'AUTH_LOGIN',
  AUTH_SIGNUP = 'AUTH_SIGNUP',
  AUTH_FORGOT_PASSWORD = 'AUTH_FORGOT_PASSWORD',
  AUTH_CONFIRM_CODE = 'AUTH_CONFIRM_CODE',
  AUTH_SET_PASSWORD = 'AUTH_SET_PASSWORD',

  MAIN_TABS = 'MAIN_TABS',
  HOME_SCREEN = 'HOME_SCREEN',
  ACCOUNT_SCREEN = 'ACCOUNT_SCREEN',
}

export default ScreenList;
