enum ScreenList {
  ONBOARDING = 'ONBOARDING',
  AUTH_LOGIN = 'AUTH_LOGIN',
  AUTH_SIGNUP = 'AUTH_SIGNUP',
  AUTH_FORGOT_PASSWORD = 'AUTH_FORGOT_PASSWORD',
  AUTH_CONFIRM_CODE = 'AUTH_CONFIRM_CODE',
  AUTH_SET_PASSWORD = 'AUTH_SET_PASSWORD',

  MAIN_TABS = 'MAIN_TABS',
  HOME = 'HOME',
  ACCOUNT = 'ACCOUNT',
  EXPLORE = 'EXPLORE',
  TICKETS = 'TICKET',
  SCAN = 'SCAN',
}

export default ScreenList;
